<a href="https://colab.research.google.com/github/RihanaRazak/Pandas-and-Numpy/blob/main/Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY (Numerical Python)**

Numpy is a python library used for working with arrays.

Import: import numpy as np

In [ ]:
#adding list
list1=[1,2,3,4]
list2=[5,6,7,8]
sum=print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8]) #for making mathematical operations easily numpy was used.
result=arr1+arr2
print(result)

[ 6  8 10 12]


In [ ]:
#accessing elements
a1=([4,5,6])
print(a1[0])

4


In [ ]:
#one dimensional array
a1=np.array([1,2,3,4,5,6,7,8,9,0]) #array() is used to create array
print(a1[0:10:2]) #slicing

[1 3 5 7 9]
1


In [ ]:
#two dimensional array
a1=np.array(([1,2,3,4],[6,7,8,9]))
print(a1.ndim)

2


In [ ]:
#three dimensional array
a1=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a1.ndim)   #ndim is used to find the dimensions

3


In [ ]:
#accessing elements in array
import numpy as np
a1=np.array([[[1,2,3],
              [4,5,6]],

              [[7,8,9],
              [1,4,7]]])
print(a1[1,1,2])

7


In [ ]:
#reshape
arr1=np.array([1,2,3,4,5,6,7,8])  #conversion of 1D array to 2D array
arr2=arr1.reshape(2,4)  #reshape converts dimensions
print(arr1)
print(arr2)
print(arr2.shape)
print(arr2.ndim) #shape tells us how many rows and columns are there in an array

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2


In [ ]:
#zeros array
a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [ ]:
#ones array
b=np.ones(5)
print(b)

[1. 1. 1. 1. 1.]


In [ ]:
#arange array
c=np.arange(1,10) #10 will not print
print(c)

[1 2 3 4 5 6 7 8 9]


In [ ]:
#linspace
d=np.linspace(0,10,4)    #randomly comes a number within the given range
print(d)                 #linspace(start,stop,how many numbers)

[ 0.          3.33333333  6.66666667 10.        ]


In [ ]:
#random
e=np.random.rand(2) #randomly 2 numbers came
print(e)

[0.24374163 0.8349731 ]


In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr[0,0,2])

3


In [ ]:
a1=np.array([1,2,3,4,5,6,7,8])
print(a1)
a2=a1.reshape(2,2,2)
print(a2)
print(a2.ndim)

[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


**PANDAS (Panel Data System)**

Pandas is an open source python library used for data cleaning, data analysis, data manipulation, and data visualization preparation.

Pandas working with Excel sheets or Tabular format datas.

**PANDAS DATA STRUCTURE:**

Pandas mainly has two types of data structure; **"Series & Data Frames"**

SERIES: It is an one dimensional labelled array.

Import: import pandas as pd

In [ ]:
#SERIES
import pandas as pd
marks=pd.Series([91,82,73,94,75])
print(marks)

0    91
1    82
2    73
3    94
4    75
dtype: int64


In [ ]:
import pandas as pd
scores=pd.Series([93,94,96,93],index=["maths","science","IT","english"])
print(scores)

maths      93
science    94
IT         96
english    93
dtype: int64


In [ ]:
import pandas as pd   #Accessing
details=pd.Series(["pass","fail"],index=["Anu","Sara"])
print(details)
print(details["Anu"])


Anu     pass
Sara    fail
dtype: object
pass


**QUESTIONS**

In [ ]:
'''what is numpy and pandas?
numpy is numerical python, it is a python library used to work with arrays.
pandas are panel data system used to work in excel sheets or tabular form datas'''

In [ ]:
'''why do we use numpy and pandas?
these are python libraries and numpy is used to work mathematical operations easily in array
pandas are used to data cleaning, data visualization, data manipulation, data analization etc..'''

In [ ]:
'''what is series?
one dimension labelled array and type of panda data structure'''

In [ ]:
'''what is the difference between list and numpy array?
list:- slower,stored different data types, limited mathematical operations.
numpy:- fast,stored same data type, support many mathematical operations.'''

In [ ]:
'''what is indexing and slicing?
indexing is used to access an element by using it's position but slicing is
used to access elements within a range by giving syntax start:stop:step '''

In [ ]:
#create a numpy array contains numbers from 1 to 20.
arr=np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#create a panda series with doctors and departments.
import pandas as pd
details=pd.Series(["sajan","john"],index=["ortho","cardio"])
print(details)

ortho     sajan
cardio     john
dtype: object
