<a href="https://colab.research.google.com/github/RihanaRazak/Pandas-and-Numpy/blob/main/Datascience_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**

IMPORTING NUMPY

In [ ]:
import numpy as np

In [ ]:
array=np.array([1,2,3])
print(array)

[1 2 3]


In [ ]:
my_array=np.array([10,20,30])
print(my_array)

[10 20 30]


1. ARITHMETIC OPERATIONS

In [ ]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(a1+a2)
print(a1-a2)
print(a1/a2)
print(a1*a2)
print(a1**a2)
print(a1%a2)

[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[ 4 10 18]
[  1  32 729]
[1 2 3]


2. COMPARISON OPERATORS

In [ ]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(a1>a2)
print(a1==a2)
print(a1!=a2)
print(a1<a2)
print(a1>=a2)
print(a1<=a2)

[False False False]
[False False False]
[ True  True  True]
[ True  True  True]
[False False False]
[ True  True  True]


3. ARRAY SHAPE OPERATIONS

In [ ]:
a1=np.array([1,2,3])  # 1 dim array
a2=np.array([[1,2,3],[4,5,6]])  # 2 dim array
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]]) # 3 dim array
print(a1.shape)
print(a2.shape)
print(a3.shape)

(3,)
(2, 3)
(1, 3, 3)


5 DIMENSION NUMPY ARRAY

In [ ]:
#TASK
a5=np.array([[[[[1,2,3],[4,5,6],[7,8,9],[1,2,3],[8,8,9]]]]])
print(a5.shape)

(1, 1, 1, 5, 3)


CONCATENATION

In [ ]:
a1=np.array([1,2,3])  #Indexing =n0,1,2
a2=np.array([4,5,6])
print(np.concatenate((a1,a2)))

[1 2 3 4 5 6]


INDEXING AND SLICING

In [ ]:
elims=np.array([10,20,30,40,50])
print(elims[-1])   #indexing
print(elims[1:4])  #slicing

50
[20 30 40]


In [ ]:
arr=np.eye((2))
print(arr)

[[1. 0.]
 [0. 1.]]


In [ ]:
arr=np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr=np.zeros(2)
print(arr)

[0. 0.]
