<a href="https://colab.research.google.com/github/RihanaRazak/Pandas-and-Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
mark=np.array([78,92,65,88,45,90,72,55])
print(mark)
print(np.sum(mark))
print(np.average(mark))
print(np.max(mark))
print(np.min(mark))

[78 92 65 88 45 90 72 55]
585
73.125
92
45


In [ ]:
#marks greater than 75
mark=np.array([78,92,65,88,45,90,72,55])
print(mark[mark>75])
#marks lesser than 50
print(mark[mark<=50])
#sorting
print(np.sort(mark))


[78 92 88 90]
[45]
[45 55 65 72 78 88 90 92]


In [ ]:
list=np.arange(1,21)
print(list)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#zeros
r=np.zeros(5)
print(r)
s=np.ones(4)
print(s)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1.]


In [ ]:
q=np.random.randint(1,100,10)
print(q)
print(np.shape(q))

[38 73 87 29 91 60 74 64 35 13]
(10,)


In [ ]:
temp=np.array([32,35,40,28,42,33])
print(np.mean(temp))
print(np.max(temp))
print(np.min(temp))

temp[temp>38]=38
print(temp)

t=temp.reshape(2,3)
print(t)

print(t[0])
print(t[:,1])

35.0
42
28
[32 35 38 28 38 33]
[[32 35 38]
 [28 38 33]]
[32 35 38]
[35 38]


In [ ]:
#slicing
a=[10,20,30,40,50,60,70,80]
print(a[0::7])
print(a[2:6:1])
print(a[::2])

[10, 80]
[30, 40, 50, 60]
[10, 30, 50, 70]


In [ ]:
a=np.array([10,20,30,40,50,60,79,80])
print(np.where(a%2==0))
print(np.where(a%2!=0))
print(a[a%2==0])
print(a[a%2!=0])

(array([0, 1, 2, 3, 4, 5, 7]),)
(array([6]),)
[10 20 30 40 50 60 80]
[79]
